### ISSUE TITLE
add some working examples 

### ISSUE THREAD

**Issue by qwertynat** [CM4all/libcommon#2]
Hi! 

Really liking this repo. would it be possible to add some demo apps on how to use some of the libraries?

For me personally i would love to see some examples on or around curl, things like 

- how to asynchronously request multiple web pages concurrently.

- how to deal with streaming http requests, i.e., firehose type http connections, where we request some data and it consistently streams until we dissconnect.

- iouring - this seems like it has gotten a lot of good press recently

many thanks

**Comment by MaxKellermann** [comment]
I added a demo program for the CURL bindings which can start an arbitrary number of parallel requests and streams response body data: https://github.com/CM4all/libcommon/blob/master/test/curl/RunHttpGet.cxx
There are already several io_uring demo programs:
- a simplified `cat` implementation: https://github.com/CM4all/libcommon/blob/master/test/uring/UringCat.cxx
- io_uring with C++20 coroutines: https://github.com/CM4all/libcommon/blob/master/test/co/RunCoReadTextFile.cxx

Here's a demo program for a PostgreSQL client with C++20 coroutines: https://github.com/CM4all/libcommon/blob/master/test/co/RunCoQuery.cxx just in case that's interesting for you

**Comment by qwertynat** [comment]
nice one! many thanks!
